import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.slogan': 'Your Trusted Partner in Global Export',
    'hero.subtitle': 'Delivering premium agricultural products worldwide with excellence and reliability',
    'hero.cta.contact': 'Contact Us',
    'hero.cta.quote': 'Get a Quote',
    'hero.cta.whatsapp': 'WhatsApp Us',
    
    // About
    'about.title': 'About BM Export',
    'about.subtitle': 'Excellence in International Trade',
    'about.description': 'BM Export is a leading international export company specializing in premium agricultural products. With years of experience and a commitment to quality, we connect producers with markets worldwide.',
    'about.expertise.title': 'International Expertise',
    'about.expertise.desc': 'Deep understanding of global markets and trade regulations',
    'about.quality.title': 'Quality & Trust',
    'about.quality.desc': 'Rigorous quality control ensuring only the finest products',
    'about.global.title': 'Global Reach',
    'about.global.desc': 'Established partnerships across continents',
    'about.stats.yearsExperience': 'Years Experience',
    'about.stats.countriesServed': 'Countries Served',
    'about.stats.happyClients': 'Happy Clients',
    'about.stats.qualityAssured': 'Quality Assured',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive Export Solutions',
    'services.agri.title': 'Agricultural Products Export',
    'services.agri.desc': 'Premium quality fruits, vegetables, and food products for international markets',
    'services.logistics.title': 'International Logistics',
    'services.logistics.desc': 'End-to-end supply chain management and shipping solutions',
    'services.packaging.title': 'Packaging & Quality Control',
    'services.packaging.desc': 'Professional packaging meeting international standards',
    'services.documentation.title': 'Export Documentation',
    'services.documentation.desc': 'Complete handling of customs and export paperwork',
    
    // Why Choose Us
    'why.title': 'Why Choose BM Export',
    'why.subtitle': 'Your Success is Our Priority',
    'why.experience.title': 'Years of Experience',
    'why.experience.desc': 'Proven track record in international trade',
    'why.quality.title': 'Quality Standards',
    'why.quality.desc': 'ISO certified quality management systems',
    'why.delivery.title': 'Worldwide Delivery',
    'why.delivery.desc': 'Reliable shipping to any destination',
    'why.pricing.title': 'Competitive Pricing',
    'why.pricing.desc': 'Best value for premium products',
    
    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'Premium Agricultural Exports',
    'products.viewDetails': 'Click on any product to view details',
    'products.clickDetails': 'Click for details',
    'products.backToCategories': 'Back to Categories',
    'products.itemsLabel': 'products',
    'products.modal.origin': 'Origin',
    'products.modal.packaging': 'Packaging',
    'products.modal.availability': 'Availability',
    'products.modal.inquire': 'Inquire Now',
    'products.modal.close': 'Close',
    
    'products.olives.title': 'Premium Olives',
    'products.olives.desc': 'Hand-picked Algerian olives',
    'products.olives.fullDesc': 'Our premium olives are hand-picked from the finest Algerian groves. Available in green and black varieties. Perfect for both retail and wholesale markets.',
    'products.olives.origin': 'Kabylie Region (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.olives.packaging': 'Containers or custom packaging',
    'products.olives.availability': 'Year-round availability',
    
    'products.dates.title': 'Deglet Nour Dates',
    'products.dates.desc': 'Finest quality Algerian dates',
    'products.dates.fullDesc': 'Deglet Nour, known as the "Queen of Dates," offers a delicate honey-like flavor and translucent appearance. Sourced directly from Algerian oases with centuries of date-growing tradition.',
    'products.dates.origin': 'Algeria - Ouargla & El Oued Oases',
    'products.dates.packaging': 'Premium boxes, bulk cartons, or branded packaging',
    'products.dates.availability': 'Seasonal harvest (October-January), available year-round',
    
    'products.citrus.title': 'Fresh Citrus',
    'products.citrus.desc': 'Sun-ripened oranges and lemons',
    'products.citrus.fullDesc': 'Vibrant, sun-ripened citrus fruits including oranges, lemons, mandarins, and grapefruits. Grown in optimal Mediterranean climate conditions for maximum sweetness and juice content.',
    'products.citrus.origin': 'Northern Algeria (Mitidja orchards)',
    'products.citrus.packaging': 'Standard fruit crates or mesh bags',
    'products.citrus.availability': 'Seasonal (November-April)',
    
    'products.food.title': 'Food Products',
    'products.food.desc': 'Juices, sweets and pastries, chocolate, and baking supplies',
    'products.food.fullDesc': 'We offer food products including Juices, Sweets and pastries, Chocolate, and Baking ingredients and supplies.',
    'products.food.origin': 'International sourcing based on request',
    'products.food.packaging': 'Retail packs, bulk cartons, or custom packaging',
    'products.food.availability': 'Year-round availability',

    'products.foodJuices.title': 'Juices',
    'products.foodJuices.desc': 'Natural and flavored juices for retail and wholesale',
    'products.foodJuices.fullDesc': 'A wide range of juices including fruit blends and classic flavors, suitable for supermarkets, distributors, and horeca channels.',
    'products.foodJuices.origin': 'International sourcing based on request',
    'products.foodJuices.packaging': 'Bottles, tetra packs, or bulk cartons',
    'products.foodJuices.availability': 'Year-round availability',

    'products.foodSweets.title': 'Sweets / Candy',
    'products.foodSweets.desc': 'Traditional and modern sweet products',
    'products.foodSweets.fullDesc': 'Sweets and pastries prepared for export markets with flexible assortments and packaging options for retail and food service.',
    'products.foodSweets.origin': 'International sourcing based on request',
    'products.foodSweets.packaging': 'Retail boxes, trays, or custom gift packs',
    'products.foodSweets.availability': 'Year-round availability',

    'products.foodChocolate.title': 'Chocolate',
    'products.foodChocolate.desc': 'Chocolate products in multiple formats',
    'products.foodChocolate.fullDesc': 'Chocolate bars, bites, and assorted selections with options for private label and custom export packaging.',
    'products.foodChocolate.origin': 'International sourcing based on request',
    'products.foodChocolate.packaging': 'Bars, pouches, boxes, or display cartons',
    'products.foodChocolate.availability': 'Year-round availability',

    'products.foodBaking.title': 'Pastry & Baking Supplies',
    'products.foodBaking.desc': 'Essential ingredients and baking supplies',
    'products.foodBaking.fullDesc': 'Baking ingredients and supplies for home and professional use, including core dry ingredients and pastry-making essentials.',
    'products.foodBaking.origin': 'International sourcing based on request',
    'products.foodBaking.packaging': 'Small retail packs, wholesale bags, or bulk cartons',
    'products.foodBaking.availability': 'Year-round availability',

    'products.foodBiscuits.title': 'Biscuits / Cookies',
    'products.foodBiscuits.desc': 'Crispy biscuits and cookies in multiple formats',
    'products.foodBiscuits.fullDesc': 'A selection of biscuits and cookies designed for export channels and wholesale buyers.',
    'products.foodBiscuits.origin': 'International sourcing based on request',
    'products.foodBiscuits.packaging': 'Flow packs and cartons',
    'products.foodBiscuits.availability': 'Year-round availability',

    'products.foodSoftDrinks.title': 'Soft Drinks / Sodas',
    'products.foodSoftDrinks.desc': 'Refreshing carbonated beverages in export-ready formats',
    'products.foodSoftDrinks.fullDesc': 'Soft drinks and sodas offered in various flavors and packaging sizes for distribution.',
    'products.foodSoftDrinks.origin': 'International sourcing based on request',
    'products.foodSoftDrinks.packaging': 'Cans and PET bottles',
    'products.foodSoftDrinks.availability': 'Year-round availability',

    'products.foodWater.title': 'Water',
    'products.foodWater.desc': 'Packaged drinking water for daily consumption',
    'products.foodWater.fullDesc': 'Clean packaged water available in multiple sizes for distribution and private label needs.',
    'products.foodWater.origin': 'International sourcing based on request',
    'products.foodWater.packaging': 'PET bottles and shrink-wrapped packs',
    'products.foodWater.availability': 'Year-round availability',

    'products.gharsDates.title': 'Ghars Dates',
    'products.gharsDates.desc': 'Traditional soft date variety',
    'products.gharsDates.fullDesc': 'Ghars dates are naturally soft and sweet, widely used for direct consumption and traditional preparations.',
    'products.gharsDates.origin': 'Algeria',
    'products.gharsDates.packaging': 'Bulk cartons or retail packs',
    'products.gharsDates.availability': 'Year-round availability',

    'products.dateSyrup.title': 'Date Syrup',
    'products.dateSyrup.desc': 'Natural sweet syrup from premium dates',
    'products.dateSyrup.fullDesc': 'Date syrup (date molasses) made from selected dates, suitable for retail, food service, and industrial use.',
    'products.dateSyrup.origin': 'Southern Algeria',
    'products.dateSyrup.packaging': 'Glass jars, squeeze bottles, or bulk containers',
    'products.dateSyrup.availability': 'Year-round availability',

    'products.datePaste.title': 'Date Paste',
    'products.datePaste.desc': 'Smooth paste for bakery and confectionery',
    'products.datePaste.fullDesc': 'Date paste with consistent texture, ideal for filling, baking, and food manufacturing.',
    'products.datePaste.origin': 'Southern Algeria',
    'products.datePaste.packaging': 'Blocks, pouches, or bulk cartons',
    'products.datePaste.availability': 'Year-round availability',

    'products.dateSugar.title': 'Date Sugar',
    'products.dateSugar.desc': 'Natural granulated sweetener from dates',
    'products.dateSugar.fullDesc': 'Date sugar as a natural alternative sweetener for bakery, beverages, and healthy food lines.',
    'products.dateSugar.origin': 'Southern Algeria',
    'products.dateSugar.packaging': 'Retail pouches or wholesale bags',
    'products.dateSugar.availability': 'Year-round availability',

    'products.dateVinegar.title': 'Date Vinegar',
    'products.dateVinegar.desc': 'Fermented vinegar made from dates',
    'products.dateVinegar.fullDesc': 'Date vinegar produced under controlled fermentation, suitable for culinary and specialty markets.',
    'products.dateVinegar.origin': 'Southern Algeria',
    'products.dateVinegar.packaging': 'Glass bottles or bulk containers',
    'products.dateVinegar.availability': 'Year-round availability',

    'products.dateCoffee.title': 'Date Coffee',
    'products.dateCoffee.desc': 'Roasted date-based caffeine-free beverage',
    'products.dateCoffee.fullDesc': 'Date coffee is a roasted date beverage alternative with rich aroma, suitable for health-conscious consumers.',
    'products.dateCoffee.origin': 'Southern Algeria',
    'products.dateCoffee.packaging': 'Retail pouches, jars, or wholesale packs',
    'products.dateCoffee.availability': 'Year-round availability',

    'products.stuffedDates.title': 'Stuffed Dates with Nuts',
    'products.stuffedDates.desc': 'Premium dates filled with selected nuts',
    'products.stuffedDates.fullDesc': 'High-quality stuffed dates filled with almonds, walnuts, or pistachios for gourmet and gift markets.',
    'products.stuffedDates.origin': 'Southern Algeria',
    'products.stuffedDates.packaging': 'Gift boxes, trays, or custom packs',
    'products.stuffedDates.availability': 'Year-round availability',

    'products.greenOlivesPitted.title': 'Green Canned Olives (Pitted)',
    'products.greenOlivesPitted.desc': 'Fresh-style green olives without pit',
    'products.greenOlivesPitted.fullDesc': 'Pitted green olives preserved in brine for retail and horeca use.',
    'products.greenOlivesPitted.origin': 'Algeria - Kabylie Region (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.greenOlivesPitted.packaging': 'Cans or pouches',
    'products.greenOlivesPitted.availability': 'Year-round availability',

    'products.blackOlivesWithPit.title': 'Black Canned Olives (With Pit)',
    'products.blackOlivesWithPit.desc': 'Fresh-style black olives with pit',
    'products.blackOlivesWithPit.fullDesc': 'Whole black olives with pit, preserved for traditional taste and export quality standards.',
    'products.blackOlivesWithPit.origin': 'Algeria - Kabylie Region (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.blackOlivesWithPit.packaging': 'Cans or pouches',
    'products.blackOlivesWithPit.availability': 'Year-round availability',

    'products.vegetablesMixA.title': 'Potato, Onion, Tomato, Broccoli',
    'products.vegetablesMixA.desc': 'Core fresh vegetables for export',
    'products.vegetablesMixA.fullDesc': 'Export-ready selection of potato, onion, tomato, and broccoli based on seasonal sourcing.',
    'products.vegetablesMixA.origin': 'Northern Algeria',
    'products.vegetablesMixA.packaging': 'Crates, cartons, or ventilated bags',
    'products.vegetablesMixA.availability': 'Seasonal and year-round by item',

    'products.potato.title': 'Potato',
    'products.potato.desc': 'Fresh export-quality potatoes',
    'products.potato.fullDesc': 'Selected fresh potatoes for export markets with consistent sizing and quality standards.',
    'products.potato.origin': 'Northern Algeria',
    'products.potato.packaging': 'Mesh bags, cartons, or bulk sacks',
    'products.potato.availability': 'Year-round availability',

    'products.onion.title': 'Onion',
    'products.onion.desc': 'Fresh onions for retail and wholesale',
    'products.onion.fullDesc': 'Fresh onions suitable for retail, wholesale, and food service channels with export-ready handling.',
    'products.onion.origin': 'Northern Algeria',
    'products.onion.packaging': 'Mesh bags, cartons, or bulk sacks',
    'products.onion.availability': 'Year-round availability',

    'products.broccoli.title': 'Broccoli',
    'products.broccoli.desc': 'Fresh broccoli for export channels',
    'products.broccoli.fullDesc': 'Fresh broccoli selected for export markets with controlled handling and quality grading.',
    'products.broccoli.origin': 'Northern Algeria',
    'products.broccoli.packaging': 'Crates, cartons, or ventilated packs',
    'products.broccoli.availability': 'Seasonal and year-round by sourcing',

    'products.carrot.title': 'Carrot',
    'products.carrot.desc': 'Fresh carrots for retail and wholesale',
    'products.carrot.fullDesc': 'Fresh carrots prepared for export supply chains with consistent quality and sizing.',
    'products.carrot.origin': 'Northern Algeria',
    'products.carrot.packaging': 'Bags, cartons, or bulk packs',
    'products.carrot.availability': 'Year-round availability',

    'products.cauliflower.title': 'Cauliflower',
    'products.cauliflower.desc': 'Fresh cauliflower for export',
    'products.cauliflower.fullDesc': 'Fresh cauliflower selected for export programs with quality grading and proper cold-chain handling.',
    'products.cauliflower.origin': 'Northern Algeria',
    'products.cauliflower.packaging': 'Crates, cartons, or ventilated packs',
    'products.cauliflower.availability': 'Seasonal and year-round by sourcing',

    'products.eggplant.title': 'Eggplant',
    'products.eggplant.desc': 'Fresh eggplant for international markets',
    'products.eggplant.fullDesc': 'Fresh eggplant prepared for export distribution with standardized sizing and packing.',
    'products.eggplant.origin': 'Northern Algeria',
    'products.eggplant.packaging': 'Crates, cartons, or bulk packs',
    'products.eggplant.availability': 'Seasonal and year-round by sourcing',

    'products.peas.title': 'Peas',
    'products.peas.desc': 'Fresh green peas',
    'products.peas.fullDesc': 'Fresh peas supplied for export and food service channels with quality-focused handling.',
    'products.peas.origin': 'Northern Algeria',
    'products.peas.packaging': 'Bags, cartons, or custom packs',
    'products.peas.availability': 'Seasonal availability',

    'products.greenBeans.title': 'Green Beans',
    'products.greenBeans.desc': 'Fresh green beans for export',
    'products.greenBeans.fullDesc': 'Fresh green beans selected for export with careful sorting and packing standards.',
    'products.greenBeans.origin': 'Northern Algeria',
    'products.greenBeans.packaging': 'Crates, cartons, or custom packs',
    'products.greenBeans.availability': 'Seasonal and year-round by sourcing',

    'products.favaBeans.title': 'Fava Beans',
    'products.favaBeans.desc': 'Fresh fava beans',
    'products.favaBeans.fullDesc': 'Fresh fava beans for export and wholesale channels with reliable quality control.',
    'products.favaBeans.origin': 'Northern Algeria',
    'products.favaBeans.packaging': 'Bags, cartons, or bulk packs',
    'products.favaBeans.availability': 'Seasonal availability',

    'products.cucumber.title': 'Cucumber',
    'products.cucumber.desc': 'Fresh cucumber for retail and export',
    'products.cucumber.fullDesc': 'Fresh cucumber prepared for export markets with proper grading and packaging.',
    'products.cucumber.origin': 'Northern Algeria',
    'products.cucumber.packaging': 'Crates, cartons, or bulk packs',
    'products.cucumber.availability': 'Year-round availability',

    'products.zucchini.title': 'Zucchini',
    'products.zucchini.desc': 'Fresh zucchini for export channels',
    'products.zucchini.fullDesc': 'Fresh zucchini supplied to export channels with quality sorting and consistent sizing.',
    'products.zucchini.origin': 'Northern Algeria',
    'products.zucchini.packaging': 'Crates, cartons, or bulk packs',
    'products.zucchini.availability': 'Seasonal and year-round by sourcing',

    'products.pumpkin.title': 'Pumpkin',
    'products.pumpkin.desc': 'Fresh pumpkin for wholesale and export',
    'products.pumpkin.fullDesc': 'Fresh pumpkin for export markets, supplied in different sizes with tailored packaging options.',
    'products.pumpkin.origin': 'Northern Algeria',
    'products.pumpkin.packaging': 'Crates, cartons, or bulk bins',
    'products.pumpkin.availability': 'Seasonal availability',

    'products.vegetablesMixB.title': 'Cauliflower, Carrot, Eggplant, Peas, Green Beans',
    'products.vegetablesMixB.desc': 'Fresh mixed vegetables selection',
    'products.vegetablesMixB.fullDesc': 'Mixed export vegetables including cauliflower, carrot, eggplant, peas, and green beans.',
    'products.vegetablesMixB.origin': 'Northern Algeria',
    'products.vegetablesMixB.packaging': 'Crates, cartons, or custom packs',
    'products.vegetablesMixB.availability': 'Seasonal and year-round by item',

    'products.vegetablesMixC.title': 'Fava Beans, Cucumber, Zucchini, Pumpkin',
    'products.vegetablesMixC.desc': 'Selected fresh vegetables',
    'products.vegetablesMixC.fullDesc': 'Export assortment including fava beans, cucumber, zucchini, and pumpkin.',
    'products.vegetablesMixC.origin': 'Northern Algeria',
    'products.vegetablesMixC.packaging': 'Crates, cartons, or custom packs',
    'products.vegetablesMixC.availability': 'Seasonal and year-round by item',

    'products.artichoke.title': 'Artichoke ',
    'products.artichoke.desc': 'Fresh artichoke for export markets',
    'products.artichoke.fullDesc': 'Premium artichoke, including regional cardoon/artichoke types, prepared for international distribution.',
    'products.artichoke.origin': 'Northern Algeria',
    'products.artichoke.packaging': 'Crates or ventilated cartons',
    'products.artichoke.availability': 'Seasonal availability',

    'products.fruitsMix.title': 'Grapes, Watermelon, Peach, Strawberry, Pomegranate',
    'products.fruitsMix.desc': 'Seasonal fresh fruits assortment',
    'products.fruitsMix.fullDesc': 'Fresh fruit range including grapes, watermelon, peach, strawberry, and pomegranate for export markets.',
    'products.fruitsMix.origin': 'Northern Algeria',
    'products.fruitsMix.packaging': 'Crates, punnets, cartons, or custom export packs',
    'products.fruitsMix.availability': 'Seasonal by fruit variety',

    'products.grapes.title': 'Grapes',
    'products.grapes.desc': 'Fresh table grapes',
    'products.grapes.fullDesc': 'Selected fresh grapes for export with controlled sorting and packing.',
    'products.grapes.origin': 'Northern Algeria',
    'products.grapes.packaging': 'Punnets, cartons, or bulk crates',
    'products.grapes.availability': 'Seasonal availability',

    'products.watermelon.title': 'Watermelon',
    'products.watermelon.desc': 'Fresh watermelon for export markets',
    'products.watermelon.fullDesc': 'Fresh watermelon selected for export programs with quality-focused handling.',
    'products.watermelon.origin': 'Northern Algeria',
    'products.watermelon.packaging': 'Bulk bins, crates, or custom export handling',
    'products.watermelon.availability': 'Seasonal availability',

    'products.peach.title': 'Peach',
    'products.peach.desc': 'Fresh peaches with export quality',
    'products.peach.fullDesc': 'Fresh peaches harvested and packed for international distribution with quality grading.',
    'products.peach.origin': 'Northern Algeria',
    'products.peach.packaging': 'Punnets, trays, or cartons',
    'products.peach.availability': 'Seasonal availability',

    'products.strawberry.title': 'Strawberry',
    'products.strawberry.desc': 'Fresh strawberries for premium markets',
    'products.strawberry.fullDesc': 'Fresh strawberries prepared for export and retail channels with cold-chain friendly packing.',
    'products.strawberry.origin': 'Northern Algeria',
    'products.strawberry.packaging': 'Punnets, clamshells, or cartons',
    'products.strawberry.availability': 'Seasonal availability',

    'products.pomegranate.title': 'Pomegranate',
    'products.pomegranate.desc': 'Fresh pomegranates for export',
    'products.pomegranate.fullDesc': 'Fresh pomegranates selected for export markets with high-quality sorting and packaging.',
    'products.pomegranate.origin': 'Northern Algeria',
    'products.pomegranate.packaging': 'Crates, cartons, or bulk packs',
    'products.pomegranate.availability': 'Seasonal availability',
    
    'products.almonds.title': 'Premium Almonds',
    'products.almonds.desc': 'Crunchy Algerian almonds',
    'products.almonds.fullDesc': 'High-quality almonds known for their rich flavor and nutritional value. Available raw, roasted, blanched, or as almond products.',
    'products.almonds.origin': 'Algerian Regions (Tlemcen, Saida, Tindouf)',
    'products.almonds.packaging': 'Vacuum-sealed bags, bulk containers, or retail packs',
    'products.almonds.availability': 'Year-round availability',
    
    'products.oliveOil.title': 'Extra Virgin Olive Oil',
    'products.oliveOil.desc': 'Cold-pressed premium oil',
    'products.oliveOil.fullDesc': 'Premium extra virgin olive oil, cold-pressed from hand-picked olives. Rich in antioxidants with a distinctive fruity flavor. Perfect for culinary and cosmetic applications.',
    'products.oliveOil.origin': 'Algeria - Kabylie Region (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.oliveOil.packaging': 'Glass bottles, tin containers, or bulk tanks',
    'products.oliveOil.availability': 'New harvest annually (November-February)',
    
    'products.tomatoes.title': 'Fresh Tomatoes',
    'products.tomatoes.desc': 'Vine-ripened export quality',
    'products.tomatoes.fullDesc': 'Premium vine-ripened tomatoes grown in optimal greenhouse and outdoor conditions. Available in various varieties including cherry, roma, and beefsteak tomatoes.',
    'products.tomatoes.origin': 'Northern Algeria',
    'products.tomatoes.packaging': 'Ventilated crates, cartons, or premium trays',
    'products.tomatoes.availability': 'Year-round with peak season (May-October)',
    
    'products.figs.title': 'Fresh & Dried Figs',
    'products.figs.desc': 'Sweet Algerian figs',
    'products.figs.fullDesc': 'Succulent figs available fresh in season or as premium dried products. Known for their natural sweetness and health benefits. Perfect for gourmet markets.',
    'products.figs.origin': 'Algeria',
    'products.figs.packaging': 'Fresh: ventilated containers; Dried: vacuum-sealed or boxes',
    'products.figs.availability': 'Fresh (August-October), Dried (year-round)',
    
    // Categories
    'category.olives': 'Olives & Olive Products',
    'category.olives.desc': 'Premium olives and traditional olive oil',
    'category.dates': 'Premium Dates',
    'category.dates.desc': 'Natural and delicious dates',
    'category.citrus': 'Fresh Citrus',
    'category.citrus.desc': 'Fresh and juicy citrus fruits',
    'category.nuts': 'Premium Nuts',
    'category.nuts.desc': 'High-quality nuts and almonds',
    'category.food': 'Food Products',
    'category.food.desc': 'Chocolate, sweets/candy, biscuits/cookies, pastry and baking supplies, soft drinks, juices, and water',
    'category.vegetables': 'Fresh Vegetables',
    'category.vegetables.desc': 'Fresh and organic vegetables',
    'category.fruits': 'Fresh Fruits',
    'category.fruits.desc': 'Natural and nutritious fruits',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in Touch',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.address': '16, Rue 1er  Nouvembre - CHLEF 02000 -Algerie',
    'contact.info.phone': '+213 5.59.30.04.17 /+213 7.75.12.98.71 /+213 5.62.08.59.02',
    'contact.info.email': 'bassatine.metidja.export@gmail.com',
    'contact.whatsapp': 'Chat on WhatsApp',
    
    // WhatsApp
    'whatsapp.message': 'Hello BM Export, I\'m interested in your export services.',
    
    // Footer
    'footer.rights': 'All Rights Reserved',
    'footer.tagline': 'Excellence in Global Export',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.products': 'Produits',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.slogan': 'Votre Partenaire de Confiance pour l\'Export Mondial',
    'hero.subtitle': 'Livraison de produits agricoles de qualité dans le monde entier avec excellence et fiabilité',
    'hero.cta.contact': 'Contactez-nous',
    'hero.cta.quote': 'Demander un Devis',
    'hero.cta.whatsapp': 'Écrivez-nous sur WhatsApp',
    
    // About
    'about.title': 'À Propos de BM Export',
    'about.subtitle': 'Excellence dans le Commerce International',
    'about.description': 'BM Export est une entreprise leader dans l\'exportation internationale, spécialisée dans les produits agricoles de qualité supérieure. Avec des années d\'expérience et un engagement envers la qualité, nous connectons les producteurs aux marchés du monde entier.',
    'about.expertise.title': 'Expertise Internationale',
    'about.expertise.desc': 'Compréhension approfondie des marchés mondiaux et des réglementations commerciales',
    'about.quality.title': 'Qualité & Confiance',
    'about.quality.desc': 'Contrôle qualité rigoureux garantissant uniquement les meilleurs produits',
    'about.global.title': 'Portée Mondiale',
    'about.global.desc': 'Partenariats établis sur tous les continents',
    'about.stats.yearsExperience': 'Années d\'expérience',
    'about.stats.countriesServed': 'Pays desservis',
    'about.stats.happyClients': 'Clients satisfaits',
    'about.stats.qualityAssured': 'Qualité garantie',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Solutions d\'Export Complètes',
    'services.agri.title': 'Export de Produits Agricoles',
    'services.agri.desc': 'Fruits, légumes et produits alimentaires de qualité pour les marchés internationaux',
    'services.logistics.title': 'Logistique Internationale',
    'services.logistics.desc': 'Gestion complète de la chaîne d\'approvisionnement et solutions d\'expédition',
    'services.packaging.title': 'Emballage & Contrôle Qualité',
    'services.packaging.desc': 'Emballage professionnel conforme aux normes internationales',
    'services.documentation.title': 'Documentation d\'Export',
    'services.documentation.desc': 'Gestion complète des formalités douanières et documents d\'exportation',
    
    // Why Choose Us
    'why.title': 'Pourquoi Choisir BM Export',
    'why.subtitle': 'Votre Succès est Notre Priorité',
    'why.experience.title': 'Années d\'Expérience',
    'why.experience.desc': 'Bilan prouvé dans le commerce international',
    'why.quality.title': 'Normes de Qualité',
    'why.quality.desc': 'Systèmes de gestion de la qualité certifiés ISO',
    'why.delivery.title': 'Livraison Mondiale',
    'why.delivery.desc': 'Expédition fiable vers toute destination',
    'why.pricing.title': 'Prix Compétitifs',
    'why.pricing.desc': 'Meilleur rapport qualité-prix pour des produits premium',
    
    // Products
    'products.title': 'Nos Produits',
    'products.subtitle': 'Exports Agricoles Premium',
    'products.viewDetails': 'Cliquez sur un produit pour voir les détails',
    'products.clickDetails': 'Voir les détails',
    'products.backToCategories': 'Retour aux catégories',
    'products.itemsLabel': 'produits',
    'products.modal.origin': 'Origine',
    'products.modal.packaging': 'Emballage',
    'products.modal.availability': 'Disponibilité',
    'products.modal.inquire': 'Demander un Devis',
    'products.modal.close': 'Fermer',
    
    'products.olives.title': 'Olives Premium',
    'products.olives.desc': 'Olives algériennes cueillies à la main',
    'products.olives.fullDesc': 'Nos olives premium sont cueillies à la main dans les meilleurs vergers algériens. Disponibles en variétés vertes et noires. Parfaites pour les marchés de détail et de gros.',
    'products.olives.origin': 'Région de Kabylie (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.olives.packaging': 'Conteneurs ou emballage personnalisé',
    'products.olives.availability': 'Disponible toute l\'année',
    
    'products.dates.title': 'Dattes Deglet Nour',
    'products.dates.desc': 'Dattes algériennes de la plus haute qualité',
    'products.dates.fullDesc': 'Deglet Nour, connue comme la "Reine des Dattes", offre une saveur délicate de miel et une apparence translucide. Provenant directement des oasis algériennes avec des siècles de tradition.',
    'products.dates.origin': 'Algérie - Oasis de Ouargla & El Oued',
    'products.dates.packaging': 'Boîtes premium, cartons en vrac ou emballage personnalisé',
    'products.dates.availability': 'Récolte saisonnière (Octobre-Janvier), disponible toute l\'année',
    
    'products.citrus.title': 'Agrumes Frais',
    'products.citrus.desc': 'Oranges et citrons mûris au soleil',
    'products.citrus.fullDesc': 'Agrumes vibrants mûris au soleil incluant oranges, citrons, mandarines et pamplemousses. Cultivés dans des conditions climatiques méditerranéennes optimales.',
    'products.citrus.origin': 'Nord de l\'Algérie (vergers de la Mitidja)',
    'products.citrus.packaging': 'Caisses standard ou sacs filet',
    'products.citrus.availability': 'Saisonnier (Novembre-Avril)',
    
    'products.food.title': 'Produits Alimentaires',
    'products.food.desc': 'Jus, sucreries et pâtisseries, chocolat, et fournitures de pâtisserie',
    'products.food.fullDesc': 'Nous proposons des produits alimentaires comprenant des jus, des sucreries et pâtisseries, du chocolat, ainsi que des ingrédients et fournitures de pâtisserie.',
    'products.food.origin': 'Approvisionnement international selon la demande',
    'products.food.packaging': 'Formats détail, cartons en vrac ou emballage personnalisé',
    'products.food.availability': 'Disponible toute l\'année',

    'products.foodJuices.title': 'Jus',
    'products.foodJuices.desc': 'Jus naturels et aromatisés pour détail et grossistes',
    'products.foodJuices.fullDesc': 'Une large gamme de jus incluant des mélanges de fruits et des saveurs classiques, adaptée aux supermarchés, distributeurs et au canal horeca.',
    'products.foodJuices.origin': 'Approvisionnement international selon la demande',
    'products.foodJuices.packaging': 'Bouteilles, briques ou cartons en vrac',
    'products.foodJuices.availability': 'Disponible toute l\'année',

    'products.foodSweets.title': 'Sucreries / Confiseries',
    'products.foodSweets.desc': 'Produits sucrés traditionnels et modernes',
    'products.foodSweets.fullDesc': 'Sucreries et pâtisseries préparées pour les marchés d\'exportation avec des assortiments et emballages flexibles pour le détail et la restauration.',
    'products.foodSweets.origin': 'Approvisionnement international selon la demande',
    'products.foodSweets.packaging': 'Boîtes détail, plateaux ou coffrets cadeaux personnalisés',
    'products.foodSweets.availability': 'Disponible toute l\'année',

    'products.foodChocolate.title': 'Chocolat',
    'products.foodChocolate.desc': 'Produits chocolatés en plusieurs formats',
    'products.foodChocolate.fullDesc': 'Tablettes, bouchées et assortiments de chocolat avec options de marque distributeur et d\'emballage export personnalisé.',
    'products.foodChocolate.origin': 'Approvisionnement international selon la demande',
    'products.foodChocolate.packaging': 'Tablettes, sachets, boîtes ou cartons présentoirs',
    'products.foodChocolate.availability': 'Disponible toute l\'année',

    'products.foodBaking.title': 'Fournitures de Patisserie & Boulangerie',
    'products.foodBaking.desc': 'Ingrédients essentiels et fournitures de pâtisserie',
    'products.foodBaking.fullDesc': 'Ingrédients et fournitures de pâtisserie pour usage domestique et professionnel, y compris les bases sèches et les essentiels de la pâtisserie.',
    'products.foodBaking.origin': 'Approvisionnement international selon la demande',
    'products.foodBaking.packaging': 'Petits formats détail, sacs grossistes ou cartons en vrac',
    'products.foodBaking.availability': 'Disponible toute l\'année',

    'products.foodBiscuits.title': 'Biscuits / Cookies',
    'products.foodBiscuits.desc': 'Biscuits et cookies croustillants en plusieurs formats',
    'products.foodBiscuits.fullDesc': 'Une sélection de biscuits et cookies adaptée aux canaux d\'exportation et aux acheteurs en gros.',
    'products.foodBiscuits.origin': 'Approvisionnement international selon la demande',
    'products.foodBiscuits.packaging': 'Sachets flow-pack et cartons',
    'products.foodBiscuits.availability': 'Disponible toute l\'année',

    'products.foodSoftDrinks.title': 'Sodas / Boissons Gazeuses',
    'products.foodSoftDrinks.desc': 'Boissons gazeuses rafraîchissantes en formats adaptés à l\'export',
    'products.foodSoftDrinks.fullDesc': 'Sodas et boissons gazeuses proposés en plusieurs saveurs et formats d\'emballage pour la distribution.',
    'products.foodSoftDrinks.origin': 'Approvisionnement international selon la demande',
    'products.foodSoftDrinks.packaging': 'Canettes et bouteilles PET',
    'products.foodSoftDrinks.availability': 'Disponible toute l\'année',

    'products.foodWater.title': 'Eau',
    'products.foodWater.desc': 'Eau potable conditionnée pour la consommation quotidienne',
    'products.foodWater.fullDesc': 'Eau conditionnée propre disponible en plusieurs formats pour la distribution et la marque privée.',
    'products.foodWater.origin': 'Approvisionnement international selon la demande',
    'products.foodWater.packaging': 'Bouteilles PET et packs sous film',
    'products.foodWater.availability': 'Disponible toute l\'année',

    'products.gharsDates.title': 'Dattes Ghars',
    'products.gharsDates.desc': 'Variété traditionnelle de dattes moelleuses',
    'products.gharsDates.fullDesc': 'Les dattes Ghars sont naturellement moelleuses et sucrées, adaptées à la consommation directe et aux préparations traditionnelles.',
    'products.gharsDates.origin': 'Algérie',
    'products.gharsDates.packaging': 'Cartons vrac ou emballages détail',
    'products.gharsDates.availability': 'Disponible toute l\'année',

    'products.dateSyrup.title': 'Sirop de dattes',
    'products.dateSyrup.desc': 'Sirop sucré naturel à base de dattes',
    'products.dateSyrup.fullDesc': 'Le sirop de dattes est fabriqué à partir de dattes sélectionnées pour le détail, la restauration et l\'industrie.',
    'products.dateSyrup.origin': 'Sud de l\'Algérie',
    'products.dateSyrup.packaging': 'Bocaux, bouteilles souples ou contenants vrac',
    'products.dateSyrup.availability': 'Disponible toute l\'année',

    'products.datePaste.title': 'Pâte de dattes',
    'products.datePaste.desc': 'Pâte lisse pour boulangerie et confiserie',
    'products.datePaste.fullDesc': 'Pâte de dattes à texture homogène, idéale pour fourrages, pâtisserie et transformation alimentaire.',
    'products.datePaste.origin': 'Sud de l\'Algérie',
    'products.datePaste.packaging': 'Blocs, sachets ou cartons vrac',
    'products.datePaste.availability': 'Disponible toute l\'année',

    'products.dateSugar.title': 'Sucre de dattes',
    'products.dateSugar.desc': 'Édulcorant naturel granulé à base de dattes',
    'products.dateSugar.fullDesc': 'Le sucre de dattes est une alternative naturelle pour la pâtisserie, les boissons et les gammes healthy.',
    'products.dateSugar.origin': 'Sud de l\'Algérie',
    'products.dateSugar.packaging': 'Sachets détail ou sacs grossistes',
    'products.dateSugar.availability': 'Disponible toute l\'année',

    'products.dateVinegar.title': 'Vinaigre de dattes',
    'products.dateVinegar.desc': 'Vinaigre fermenté à base de dattes',
    'products.dateVinegar.fullDesc': 'Vinaigre de dattes produit par fermentation contrôlée pour les usages culinaires et marchés spécialisés.',
    'products.dateVinegar.origin': 'Sud de l\'Algérie',
    'products.dateVinegar.packaging': 'Bouteilles en verre ou contenants vrac',
    'products.dateVinegar.availability': 'Disponible toute l\'année',

    'products.dateCoffee.title': 'Café de dattes',
    'products.dateCoffee.desc': 'Boisson torréfiée à base de dattes sans caféine',
    'products.dateCoffee.fullDesc': 'Le café de dattes est une alternative torréfiée au profil aromatique riche, adaptée aux consommateurs soucieux de santé.',
    'products.dateCoffee.origin': 'Sud de l\'Algérie',
    'products.dateCoffee.packaging': 'Sachets, bocaux ou formats grossistes',
    'products.dateCoffee.availability': 'Disponible toute l\'année',

    'products.stuffedDates.title': 'Dattes farcies aux fruits secs',
    'products.stuffedDates.desc': 'Dattes premium farcies avec fruits secs sélectionnés',
    'products.stuffedDates.fullDesc': 'Dattes de haute qualité farcies aux amandes, noix ou pistaches pour les marchés gourmets et cadeaux.',
    'products.stuffedDates.origin': 'Sud de l\'Algérie',
    'products.stuffedDates.packaging': 'Coffrets, plateaux ou emballages personnalisés',
    'products.stuffedDates.availability': 'Disponible toute l\'année',

    'products.greenOlivesPitted.title': 'Olives vertes en conserve (dénoyautées)',
    'products.greenOlivesPitted.desc': 'Olives vertes style frais sans noyau',
    'products.greenOlivesPitted.fullDesc': 'Olives vertes dénoyautées conservées en saumure pour le détail et la restauration.',
    'products.greenOlivesPitted.origin': 'Algérie - Région de Kabylie (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.greenOlivesPitted.packaging': 'Boîtes ou sachets',
    'products.greenOlivesPitted.availability': 'Disponible toute l\'année',

    'products.blackOlivesWithPit.title': 'Olives noires en conserve (avec noyau)',
    'products.blackOlivesWithPit.desc': 'Olives noires style frais avec noyau',
    'products.blackOlivesWithPit.fullDesc': 'Olives noires entières avec noyau, conservées pour un goût traditionnel et une qualité export.',
    'products.blackOlivesWithPit.origin': 'Algérie - Région de Kabylie (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.blackOlivesWithPit.packaging': 'Boîtes ou sachets',
    'products.blackOlivesWithPit.availability': 'Disponible toute l\'année',

    'products.vegetablesMixA.title': 'Pomme de terre, oignon, tomate, brocoli',
    'products.vegetablesMixA.desc': 'Légumes de base frais pour export',
    'products.vegetablesMixA.fullDesc': 'Sélection export de pommes de terre, oignons, tomates et brocolis selon disponibilité saisonnière.',
    'products.vegetablesMixA.origin': 'Nord de l\'Algérie',
    'products.vegetablesMixA.packaging': 'Caisses, cartons ou sacs ventilés',
    'products.vegetablesMixA.availability': 'Saisonnier et annuel selon produit',

    'products.potato.title': 'Pomme de terre',
    'products.potato.desc': 'Pommes de terre fraîches qualité export',
    'products.potato.fullDesc': 'Pommes de terre fraîches sélectionnées pour les marchés d\'exportation avec calibres et qualité réguliers.',
    'products.potato.origin': 'Nord de l\'Algérie',
    'products.potato.packaging': 'Sacs filet, cartons ou sacs vrac',
    'products.potato.availability': 'Disponible toute l\'année',

    'products.onion.title': 'Oignon',
    'products.onion.desc': 'Oignons frais pour détail et grossistes',
    'products.onion.fullDesc': 'Oignons frais adaptés aux circuits détail, grossiste et restauration avec préparation export.',
    'products.onion.origin': 'Nord de l\'Algérie',
    'products.onion.packaging': 'Sacs filet, cartons ou sacs vrac',
    'products.onion.availability': 'Disponible toute l\'année',

    'products.broccoli.title': 'Brocoli',
    'products.broccoli.desc': 'Brocoli frais pour circuits d\'export',
    'products.broccoli.fullDesc': 'Brocoli frais sélectionné pour les marchés d\'exportation avec tri et contrôle qualité.',
    'products.broccoli.origin': 'Nord de l\'Algérie',
    'products.broccoli.packaging': 'Caisses, cartons ou emballages ventilés',
    'products.broccoli.availability': 'Saisonnier et annuel selon approvisionnement',

    'products.carrot.title': 'Carotte',
    'products.carrot.desc': 'Carottes fraîches pour détail et grossistes',
    'products.carrot.fullDesc': 'Carottes fraîches préparées pour l\'export avec calibres et qualité réguliers.',
    'products.carrot.origin': 'Nord de l\'Algérie',
    'products.carrot.packaging': 'Sacs, cartons ou formats vrac',
    'products.carrot.availability': 'Disponible toute l\'année',

    'products.cauliflower.title': 'Chou-fleur',
    'products.cauliflower.desc': 'Chou-fleur frais pour export',
    'products.cauliflower.fullDesc': 'Chou-fleur frais sélectionné pour l\'exportation avec tri qualité et logistique adaptée à la chaîne du froid.',
    'products.cauliflower.origin': 'Nord de l\'Algérie',
    'products.cauliflower.packaging': 'Caisses, cartons ou emballages ventilés',
    'products.cauliflower.availability': 'Saisonnier et annuel selon approvisionnement',

    'products.eggplant.title': 'Aubergine',
    'products.eggplant.desc': 'Aubergine fraîche pour marchés internationaux',
    'products.eggplant.fullDesc': 'Aubergine fraîche préparée pour l\'export avec calibres et conditionnement standardisés.',
    'products.eggplant.origin': 'Nord de l\'Algérie',
    'products.eggplant.packaging': 'Caisses, cartons ou formats vrac',
    'products.eggplant.availability': 'Saisonnier et annuel selon approvisionnement',

    'products.peas.title': 'Petits pois',
    'products.peas.desc': 'Petits pois verts frais',
    'products.peas.fullDesc': 'Petits pois frais destinés à l\'export et à la restauration avec manutention orientée qualité.',
    'products.peas.origin': 'Nord de l\'Algérie',
    'products.peas.packaging': 'Sacs, cartons ou emballages personnalisés',
    'products.peas.availability': 'Disponibilité saisonnière',

    'products.greenBeans.title': 'Haricots verts',
    'products.greenBeans.desc': 'Haricots verts frais pour export',
    'products.greenBeans.fullDesc': 'Haricots verts frais sélectionnés pour l\'export avec tri et conditionnement soignés.',
    'products.greenBeans.origin': 'Nord de l\'Algérie',
    'products.greenBeans.packaging': 'Caisses, cartons ou emballages personnalisés',
    'products.greenBeans.availability': 'Saisonnier et annuel selon approvisionnement',

    'products.favaBeans.title': 'Fèves',
    'products.favaBeans.desc': 'Fèves fraîches',
    'products.favaBeans.fullDesc': 'Fèves fraîches pour les circuits export et grossistes avec contrôle qualité régulier.',
    'products.favaBeans.origin': 'Nord de l\'Algérie',
    'products.favaBeans.packaging': 'Sacs, cartons ou formats vrac',
    'products.favaBeans.availability': 'Disponibilité saisonnière',

    'products.cucumber.title': 'Concombre',
    'products.cucumber.desc': 'Concombre frais pour détail et export',
    'products.cucumber.fullDesc': 'Concombre frais préparé pour les marchés d\'exportation avec tri et emballage adaptés.',
    'products.cucumber.origin': 'Nord de l\'Algérie',
    'products.cucumber.packaging': 'Caisses, cartons ou formats vrac',
    'products.cucumber.availability': 'Disponible toute l\'année',

    'products.zucchini.title': 'Courgette',
    'products.zucchini.desc': 'Courgette fraîche pour circuits export',
    'products.zucchini.fullDesc': 'Courgette fraîche destinée à l\'export avec calibres homogènes et conditionnement contrôlé.',
    'products.zucchini.origin': 'Nord de l\'Algérie',
    'products.zucchini.packaging': 'Caisses, cartons ou formats vrac',
    'products.zucchini.availability': 'Saisonnier et annuel selon approvisionnement',

    'products.pumpkin.title': 'Potiron',
    'products.pumpkin.desc': 'Potiron frais pour grossistes et export',
    'products.pumpkin.fullDesc': 'Potiron frais pour marchés d\'exportation, disponible en différents calibres avec emballages adaptés.',
    'products.pumpkin.origin': 'Nord de l\'Algérie',
    'products.pumpkin.packaging': 'Caisses, cartons ou bacs vrac',
    'products.pumpkin.availability': 'Disponibilité saisonnière',

    'products.vegetablesMixB.title': 'Chou-fleur, carotte, aubergine, petits pois, haricots verts',
    'products.vegetablesMixB.desc': 'Sélection de légumes frais variés',
    'products.vegetablesMixB.fullDesc': 'Assortiment de légumes export comprenant chou-fleur, carottes, aubergines, petits pois et haricots verts.',
    'products.vegetablesMixB.origin': 'Nord de l\'Algérie',
    'products.vegetablesMixB.packaging': 'Caisses, cartons ou emballages personnalisés',
    'products.vegetablesMixB.availability': 'Saisonnier et annuel selon produit',

    'products.vegetablesMixC.title': 'Fèves, concombre, courgette, potiron',
    'products.vegetablesMixC.desc': 'Légumes frais sélectionnés',
    'products.vegetablesMixC.fullDesc': 'Assortiment export incluant fèves, concombre, courgette et potiron.',
    'products.vegetablesMixC.origin': 'Nord de l\'Algérie',
    'products.vegetablesMixC.packaging': 'Caisses, cartons ou emballages personnalisés',
    'products.vegetablesMixC.availability': 'Saisonnier et annuel selon produit',

    'products.artichoke.title': 'Artichaut (type cardon)',
    'products.artichoke.desc': 'Artichaut frais pour marchés d\'export',
    'products.artichoke.fullDesc': 'Artichaut premium, y compris types régionaux cardon/artichaut, préparé pour la distribution internationale.',
    'products.artichoke.origin': 'Nord de l\'Algérie',
    'products.artichoke.packaging': 'Caisses ou cartons ventilés',
    'products.artichoke.availability': 'Disponibilité saisonnière',

    'products.fruitsMix.title': 'Raisin, pastèque, pêche, fraise, grenade',
    'products.fruitsMix.desc': 'Assortiment de fruits frais saisonniers',
    'products.fruitsMix.fullDesc': 'Gamme de fruits frais incluant raisin, pastèque, pêche, fraise et grenade pour les marchés d\'exportation.',
    'products.fruitsMix.origin': 'Nord de l\'Algérie',
    'products.fruitsMix.packaging': 'Caisses, barquettes, cartons ou packs personnalisés',
    'products.fruitsMix.availability': 'Saisonnier selon variété',

    'products.grapes.title': 'Raisin',
    'products.grapes.desc': 'Raisins de table frais',
    'products.grapes.fullDesc': 'Raisins frais sélectionnés pour l\'exportation avec tri et conditionnement contrôlés.',
    'products.grapes.origin': 'Nord de l\'Algérie',
    'products.grapes.packaging': 'Barquettes, cartons ou caisses vrac',
    'products.grapes.availability': 'Disponibilité saisonnière',

    'products.watermelon.title': 'Pastèque',
    'products.watermelon.desc': 'Pastèque fraîche pour marchés export',
    'products.watermelon.fullDesc': 'Pastèque fraîche sélectionnée pour les programmes d\'exportation avec manutention orientée qualité.',
    'products.watermelon.origin': 'Nord de l\'Algérie',
    'products.watermelon.packaging': 'Bacs vrac, caisses ou manutention export personnalisée',
    'products.watermelon.availability': 'Disponibilité saisonnière',

    'products.peach.title': 'Pêche',
    'products.peach.desc': 'Pêches fraîches qualité export',
    'products.peach.fullDesc': 'Pêches fraîches récoltées et conditionnées pour la distribution internationale.',
    'products.peach.origin': 'Nord de l\'Algérie',
    'products.peach.packaging': 'Barquettes, plateaux ou cartons',
    'products.peach.availability': 'Disponibilité saisonnière',

    'products.strawberry.title': 'Fraise',
    'products.strawberry.desc': 'Fraises fraîches pour marchés premium',
    'products.strawberry.fullDesc': 'Fraises fraîches préparées pour l\'export et le détail avec emballage adapté à la chaîne du froid.',
    'products.strawberry.origin': 'Nord de l\'Algérie',
    'products.strawberry.packaging': 'Barquettes, clamshells ou cartons',
    'products.strawberry.availability': 'Disponibilité saisonnière',

    'products.pomegranate.title': 'Grenade',
    'products.pomegranate.desc': 'Grenades fraîches pour export',
    'products.pomegranate.fullDesc': 'Grenades fraîches sélectionnées pour les marchés d\'exportation avec tri et emballage de qualité.',
    'products.pomegranate.origin': 'Nord de l\'Algérie',
    'products.pomegranate.packaging': 'Caisses, cartons ou formats vrac',
    'products.pomegranate.availability': 'Disponibilité saisonnière',
    
    'products.almonds.title': 'Amandes Premium',
    'products.almonds.desc': 'Amandes algériennes croquantes',
    'products.almonds.fullDesc': 'Amandes de haute qualité connues pour leur saveur riche et leur valeur nutritionnelle. Disponibles crues, grillées, mondées ou en produits dérivés.',
    'products.almonds.origin': 'Régions algériennes (Tlemcen, Saida, Tindouf)',
    'products.almonds.packaging': 'Sacs sous vide, conteneurs en vrac ou packs de détail',
    'products.almonds.availability': 'Disponible toute l\'année',
    
    'products.oliveOil.title': 'Huile d\'Olive Extra Vierge',
    'products.oliveOil.desc': 'Huile premium pressée à froid',
    'products.oliveOil.fullDesc': 'Huile d\'olive extra vierge premium, pressée à froid à partir d\'olives cueillies à la main. Riche en antioxydants avec une saveur fruitée distinctive.',
    'products.oliveOil.origin': 'Algérie - Région de Kabylie (Tizi Ouzou, Bejaia, Boumerdes)',
    'products.oliveOil.packaging': 'Bouteilles en verre, bidons ou citernes en vrac',
    'products.oliveOil.availability': 'Nouvelle récolte annuelle (Novembre-Février)',
    
    'products.tomatoes.title': 'Tomates Fraîches',
    'products.tomatoes.desc': 'Qualité export mûries sur pied',
    'products.tomatoes.fullDesc': 'Tomates premium mûries sur pied cultivées en conditions optimales de serre et plein air. Disponibles en diverses variétés dont cerises, roma et cœur de bœuf.',
    'products.tomatoes.origin': 'Nord de l\'Algérie',
    'products.tomatoes.packaging': 'Caisses ventilées, cartons ou plateaux premium',
    'products.tomatoes.availability': 'Toute l\'année avec pic de saison (Mai-Octobre)',
    
    'products.figs.title': 'Figues Fraîches & Séchées',
    'products.figs.desc': 'Figues algériennes sucrées',
    'products.figs.fullDesc': 'Figues succulentes disponibles fraîches en saison ou en produits séchés premium. Connues pour leur douceur naturelle et leurs bienfaits pour la santé.',
    'products.figs.origin': 'Algérie',
    'products.figs.packaging': 'Fraîches: conteneurs ventilés; Séchées: sous vide ou boîtes',
    'products.figs.availability': 'Fraîches (Août-Octobre), Séchées (toute l\'année)',
    
    // Categories
    'category.olives': 'Olives & Produits Olive',
    'category.olives.desc': 'Olives premium et l\'huile d\'olive traditionnelle',
    'category.dates': 'Dattes Premium',
    'category.dates.desc': 'Dattes naturelles et délicieuses',
    'category.citrus': 'Agrumes Frais',
    'category.citrus.desc': 'Agrumes frais et succulents',
    'category.nuts': 'Noix Premium',
    'category.nuts.desc': 'Noix et amandes de haute qualité',
    'category.food': 'Produits Alimentaires',
    'category.food.desc': 'Chocolat, sucreries/confiseries, biscuits/cookies, fournitures de pâtisserie, sodas, jus et eau',
    'category.vegetables': 'Légumes Frais',
    'category.vegetables.desc': 'Légumes frais et biologiques',
    'category.fruits': 'Fruits Frais',
    'category.fruits.desc': 'Fruits naturels et nutritifs',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Prenez Contact',
    'contact.form.name': 'Votre Nom',
    'contact.form.email': 'Adresse Email',
    'contact.form.phone': 'Numéro de Téléphone',
    'contact.form.message': 'Votre Message',
    'contact.form.submit': 'Envoyer le Message',
    'contact.info.title': 'Informations de Contact',
    'contact.info.address': '16, Rue 1er  Nouvembre - CHLEF 02000 -Algerie',
    'contact.info.phone': '+213 5.59.30.04.17 /+213 7.75.12.98.71 /+213 5.62.08.59.02',
    'contact.info.email': 'bassatine.metidja.export@gmail.com',
    'contact.whatsapp': 'Discuter sur WhatsApp',
    
    // WhatsApp
    'whatsapp.message': 'Bonjour BM Export, je suis intéressé par vos services d\'exportation.',
    
    // Footer
    'footer.rights': 'Tous Droits Réservés',
    'footer.tagline': 'Excellence dans l\'Export Mondial',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'خدماتنا',
    'nav.products': 'منتجاتنا',
    'nav.contact': 'اتصل بنا',
    
    // Hero
    'hero.slogan': 'شريكك الموثوق في التصدير العالمي',
    'hero.subtitle': 'توصيل المنتجات الزراعية الممتازة إلى جميع أنحاء العالم بتميز وموثوقية',
    'hero.cta.contact': 'اتصل بنا',
    'hero.cta.quote': 'احصل على عرض سعر',
    'hero.cta.whatsapp': 'تواصل عبر واتساب',
    
    // About
    'about.title': 'عن BM Export',
    'about.subtitle': 'التميز في التجارة الدولية',
    'about.description': 'BM Export هي شركة رائدة في التصدير الدولي متخصصة في المنتجات الزراعية الممتازة. مع سنوات من الخبرة والالتزام بالجودة، نربط المنتجين بالأسواق في جميع أنحاء العالم.',
    'about.expertise.title': 'خبرة دولية',
    'about.expertise.desc': 'فهم عميق للأسواق العالمية ولوائح التجارة',
    'about.quality.title': 'الجودة والثقة',
    'about.quality.desc': 'رقابة صارمة على الجودة تضمن أفضل المنتجات فقط',
    'about.global.title': 'انتشار عالمي',
    'about.global.desc': 'شراكات راسخة عبر القارات',
    'about.stats.yearsExperience': 'سنوات الخبرة',
    'about.stats.countriesServed': 'الدول المخدومة',
    'about.stats.happyClients': 'عملاء سعداء',
    'about.stats.qualityAssured': 'جودة مضمونة',
    
    // Services
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول تصدير شاملة',
    'services.agri.title': 'تصدير المنتجات الزراعية',
    'services.agri.desc': 'فواكه وخضروات والمواد الغذائية ذات الجودة للأسواق الدولية',
    'services.logistics.title': 'الخدمات اللوجستية الدولية',
    'services.logistics.desc': 'إدارة سلسلة التوريد الشاملة وحلول الشحن',
    'services.packaging.title': 'التعبئة ومراقبة الجودة',
    'services.packaging.desc': 'تعبئة احترافية تلبي المعايير الدولية',
    'services.documentation.title': 'وثائق التصدير',
    'services.documentation.desc': 'التعامل الكامل مع الجمارك وأوراق التصدير',
    
    // Why Choose Us
    'why.title': 'لماذا تختار BM Export',
    'why.subtitle': 'نجاحك هو أولويتنا',
    'why.experience.title': 'سنوات من الخبرة',
    'why.experience.desc': 'سجل حافل في التجارة الدولية',
    'why.quality.title': 'معايير الجودة',
    'why.quality.desc': 'أنظمة إدارة الجودة معتمدة من ISO',
    'why.delivery.title': 'التوصيل العالمي',
    'why.delivery.desc': 'شحن موثوق إلى أي وجهة',
    'why.pricing.title': 'أسعار تنافسية',
    'why.pricing.desc': 'أفضل قيمة للمنتجات الممتازة',
    
    // Products
    'products.title': 'منتجاتنا',
    'products.subtitle': 'صادرات زراعية ممتازة',
    'products.viewDetails': 'انقر على أي منتج لعرض التفاصيل',
    'products.clickDetails': 'انقر للتفاصيل',
    'products.backToCategories': 'العودة إلى الفئات',
    'products.itemsLabel': 'منتج',
    'products.modal.origin': 'المنشأ',
    'products.modal.packaging': 'التعبئة',
    'products.modal.availability': 'التوفر',
    'products.modal.inquire': 'استفسر الآن',
    'products.modal.close': 'إغلاق',
    
    'products.olives.title': 'زيتون ممتاز',
    'products.olives.desc': 'زيتون جزائري منتقى يدوياً',
    'products.olives.fullDesc': 'زيتوننا الممتاز منتقى يدوياً من أفضل البساتين الجزائرية. متوفر بأنواع مختلفة منها  والأخضر والأسود. مثالي لأسواق التجزئة والجملة.',
    'products.olives.origin': 'منطقة القبائل  (تزي وزو， بجاية， بومرداس)',
    'products.olives.packaging': 'حاويات أو تعبئة مخصصة',
    'products.olives.availability': 'متوفر على مدار السنة',
    
    'products.dates.title': 'تمر دقلة نور',
    'products.dates.desc': 'تمور جزائرية من أعلى جودة',
    'products.dates.fullDesc': 'دقلة نور، المعروفة بـ "ملكة التمور"، تقدم نكهة عسلية رقيقة ومظهراً شفافاً. مصدرها مباشرة من واحات جزائر مع قرون من التقاليد.',
    'products.dates.origin': 'جزائر - واحات ورقلة و وادي سوف ي',
    'products.dates.packaging': 'علب فاخرة، صناديق  أو تعبئة مخصصة',
    'products.dates.availability': 'موسم الحصاد ، متوفر على مدار السنة',
    
    'products.citrus.title': 'حمضيات طازجة',
    'products.citrus.desc': 'برتقال وليمون ناضج تحت الشمس',
    'products.citrus.fullDesc': 'حمضيات نابضة بالحياة ناضجة تحت الشمس تشمل البرتقال والليمون واليوسفي والجريب فروت. تزرع في ظروف مناخية متوسطية مثالية.',
    'products.citrus.origin': 'شمال الجزائر (بساتين متيجة)',
    'products.citrus.packaging': 'صناديق فاكهة قياسية، أكياس شبكية',
    'products.citrus.availability': 'موسمي (نوفمبر-أبريل)',
    
    'products.food.title': 'مواد غذائية',
    'products.food.desc': 'عصائر، حلويات ومعجنات، شوكولاتة، ومستلزمات الخبز',
    'products.food.fullDesc': 'نوفر مواد غذائية تشمل: عصائر، حلويات ومعجنات، شوكولاتة، ومكونات ومستلزمات الخبز.',
    'products.food.origin': 'توريد دولي حسب الطلب',
    'products.food.packaging': 'عبوات تجزئة، كراتين جملة أو تعبئة مخصصة',
    'products.food.availability': 'متوفر على مدار السنة',

    'products.foodJuices.title': 'عصائر',
    'products.foodJuices.desc': 'عصائر طبيعية ومنكّهة للتجزئة والجملة',
    'products.foodJuices.fullDesc': 'تشكيلة متنوعة من العصائر تشمل خلطات الفواكه والنكهات الكلاسيكية، مناسبة للمتاجر والموزعين وقطاع المطاعم والفنادق.',
    'products.foodJuices.origin': 'توريد دولي حسب الطلب',
    'products.foodJuices.packaging': 'زجاجات، عبوات كرتونية أو كراتين جملة',
    'products.foodJuices.availability': 'متوفر على مدار السنة',

    'products.foodSweets.title': 'حلويات / سكاكر',
    'products.foodSweets.desc': 'منتجات حلوة تقليدية وعصرية',
    'products.foodSweets.fullDesc': 'حلويات ومعجنات مهيأة لأسواق التصدير مع خيارات متنوعة في التشكيلة والتعبئة للتجزئة وخدمات الأغذية.',
    'products.foodSweets.origin': 'توريد دولي حسب الطلب',
    'products.foodSweets.packaging': 'علب تجزئة، صواني أو عبوات هدايا مخصصة',
    'products.foodSweets.availability': 'متوفر على مدار السنة',

    'products.foodChocolate.title': 'شوكولاتة',
    'products.foodChocolate.desc': 'منتجات شوكولاتة بأشكال متعددة',
    'products.foodChocolate.fullDesc': 'ألواح شوكولاتة وقطع متنوعة وتشكيلات مختلفة مع إمكانية العلامة الخاصة وتعبئة تصدير مخصصة.',
    'products.foodChocolate.origin': 'توريد دولي حسب الطلب',
    'products.foodChocolate.packaging': ' أكياس، علب أو كراتين عرض',
    'products.foodChocolate.availability': 'متوفر على مدار السنة',

    'products.foodBaking.title': 'مستلزمات المعجنات والخبز',
    'products.foodBaking.desc': 'مكونات أساسية ومستلزمات للخبز والحلويات',
    'products.foodBaking.fullDesc': 'مكونات ومستلزمات الخبز للاستخدام المنزلي والمهني، وتشمل المواد الأساسية الجافة ولوازم صناعة الحلويات.',
    'products.foodBaking.origin': 'توريد دولي حسب الطلب',
    'products.foodBaking.packaging': 'عبوات صغيرة للتجزئة، أكياس جملة أو كراتين كبيرة',
    'products.foodBaking.availability': 'متوفر على مدار السنة',

    'products.foodBiscuits.title': 'بسكويت / كوكيز',
    'products.foodBiscuits.desc': 'بسكويت وكوكيز مقرمشة بعدة أحجام وتنسيقات',
    'products.foodBiscuits.fullDesc': 'تشكيلة من البسكويت والكوكيز مناسبة لقنوات التصدير والعملاء بالجملة.',
    'products.foodBiscuits.origin': 'توريد دولي حسب الطلب',
    'products.foodBiscuits.packaging': 'أكياس فلو باك وكراتين',
    'products.foodBiscuits.availability': 'متوفر على مدار السنة',

    'products.foodSoftDrinks.title': 'مشروبات غازية / صودا',
    'products.foodSoftDrinks.desc': 'مشروبات غازية منعشة بعبوات مناسبة للتصدير',
    'products.foodSoftDrinks.fullDesc': 'نوفر مشروبات غازية وصودا بنكهات متعددة وأحجام تعبئة مختلفة للتوزيع.',
    'products.foodSoftDrinks.origin': 'توريد دولي حسب الطلب',
    'products.foodSoftDrinks.packaging': 'علب وبوتل PET',
    'products.foodSoftDrinks.availability': 'متوفر على مدار السنة',

    'products.foodWater.title': 'مياه',
    'products.foodWater.desc': 'مياه شرب معبأة للاستهلاك اليومي',
    'products.foodWater.fullDesc': 'مياه شرب نقية معبأة ومتوفرة بأحجام مختلفة للتوزيع والعلامة الخاصة.',
    'products.foodWater.origin': 'توريد دولي حسب الطلب',
    'products.foodWater.packaging': 'عبوات PET وباقات مغلفة',
    'products.foodWater.availability': 'متوفر على مدار السنة',

    'products.gharsDates.title': 'تمر الغرس',
    'products.gharsDates.desc': 'صنف تمر تقليدي طري',
    'products.gharsDates.fullDesc': 'تمر الغرس يتميز بقوامه الطري وحلاوته الطبيعية، مناسب للاستهلاك المباشر والتحضيرات التقليدية.',
    'products.gharsDates.origin': 'الجزائر ',
    'products.gharsDates.packaging': 'كراتين جملة أو عبوات تجزئة',
    'products.gharsDates.availability': 'متوفر على مدار السنة',

    'products.dateSyrup.title': 'دبس التمر',
    'products.dateSyrup.desc': 'شراب طبيعي محلى من التمر',
    'products.dateSyrup.fullDesc': 'دبس التمر مصنوع من تمور مختارة ومناسب للتجزئة وخدمات الأغذية والاستخدام الصناعي.',
    'products.dateSyrup.origin': 'جنوب الجزائٍر',
    'products.dateSyrup.packaging': 'مرطبانات زجاجية،  حاويات جملة',
    'products.dateSyrup.availability': 'متوفر على مدار السنة',

    'products.datePaste.title': 'عجينة التمر',
    'products.datePaste.desc': 'عجينة ناعمة للمخبوزات والحلويات',
    'products.datePaste.fullDesc': 'عجينة تمر بقوام متجانس مثالية للحشوات وصناعة الحلويات والتصنيع الغذائي.',
    'products.datePaste.origin': 'جنوب الجزائٍر',
    'products.datePaste.packaging': 'قوالب، أكياس أو كراتين جملة',
    'products.datePaste.availability': 'متوفر على مدار السنة',

    'products.dateSugar.title': 'سكر التمر',
    'products.dateSugar.desc': 'محلي طبيعي حبيبي من التمر',
    'products.dateSugar.fullDesc': 'سكر التمر بديل طبيعي للتحلية في المخبوزات والمشروبات والمنتجات الصحية.',
    'products.dateSugar.origin': 'جنوب الجزائر',
    'products.dateSugar.packaging': 'أكياس تجزئة أو أكياس جملة',
    'products.dateSugar.availability': 'متوفر على مدار السنة',

    'products.dateVinegar.title': 'خل التمر',
    'products.dateVinegar.desc': 'خل مخمر مصنوع من التمر',
    'products.dateVinegar.fullDesc': 'خل التمر يتم إنتاجه بتخمير مضبوط ومناسب للاستخدامات الغذائية والأسواق المتخصصة.',
     'products.dateVinegar.origin': 'جنوب الجزائر',
    'products.dateVinegar.packaging': 'زجاجات زجاجية أو حاويات جملة',
    'products.dateVinegar.availability': 'متوفر على مدار السنة',

    'products.dateCoffee.title': 'قهوة التمر',
    'products.dateCoffee.desc': 'مشروب محمص من التمر خالٍ من الكافيين',
    'products.dateCoffee.fullDesc': 'قهوة التمر بديل محمص بنكهة غنية، مناسب للمستهلكين المهتمين بالخيارات الصحية.',
    'products.dateCoffee.origin': 'جنوب الجزائر',
    'products.dateCoffee.packaging': 'أكياس تجزئة، مرطبانات أو عبوات جملة',
    'products.dateCoffee.availability': 'متوفر على مدار السنة',

    'products.stuffedDates.title': 'تمر محشو بالمكسرات',
    'products.stuffedDates.desc': 'تمور فاخرة محشوة بمكسرات مختارة',
    'products.stuffedDates.fullDesc': 'تمور عالية الجودة محشوة باللوز أو الجوز أو الفستق، مناسبة للأسواق الفاخرة والهدايا.',
    'products.stuffedDates.origin': 'جنوب الجزائر',
    'products.stuffedDates.packaging': 'علب هدايا، صواني أو عبوات مخصصة',
    'products.stuffedDates.availability': 'متوفر على مدار السنة',

    'products.greenOlivesPitted.title': 'زيتون أخضر مصبر (بدون نواة)',
    'products.greenOlivesPitted.desc': 'زيتون أخضر مصبر بجودة تصديرية',
    'products.greenOlivesPitted.fullDesc': 'زيتون أخضر بدون نواة محفوظ في محلول ملحي ومناسب للتجزئة وقطاع المطاعم.',
    'products.greenOlivesPitted.origin': 'الجزائر - منطقة القبائل (تيزي وزو، بجاية، بومرداس)',
    'products.greenOlivesPitted.packaging': 'علب، أكياس و ',
    'products.greenOlivesPitted.availability': 'متوفر على مدار السنة',

    'products.blackOlivesWithPit.title': 'زيتون أسود مصبر (بالنواة)',
    'products.blackOlivesWithPit.desc': 'زيتون أسود مصبر بالطعم التقليدي',
    'products.blackOlivesWithPit.fullDesc': 'زيتون أسود كامل بالنواة محفوظ بمعايير جودة تصديرية ونكهة تقليدية.',
    'products.blackOlivesWithPit.origin': 'الجزائر - منطقة القبائل  (تيزي وزو، بجاية، بومرداس)',
    'products.blackOlivesWithPit.packaging': 'علب، أكياس',
    'products.blackOlivesWithPit.availability': 'متوفر على مدار السنة',

    'products.vegetablesMixA.title': 'بطاطا، بصل، طماطم، بروكلي',
    'products.vegetablesMixA.desc': 'خضروات أساسية طازجة للتصدير',
    'products.vegetablesMixA.fullDesc': 'تشكيلة تصديرية من البطاطا والبصل والطماطم والبروكلي حسب التوفر الموسمي.',
    'products.vegetablesMixA.origin': 'شمال الجزائر',
    'products.vegetablesMixA.packaging': 'صناديق، كراتين أو أكياس مهواة',
    'products.vegetablesMixA.availability': 'موسمي وعلى مدار السنة حسب الصنف',

    'products.potato.title': 'بطاطا',
    'products.potato.desc': 'بطاطا طازجة بجودة تصديرية',
    'products.potato.fullDesc': 'بطاطا طازجة مختارة للتصدير بمواصفات جودة وفرز متناسق.',
    'products.potato.origin': 'شمال الجزائر',
    'products.potato.packaging': 'أكياس شبكية، كراتين أو أكياس جملة',
    'products.potato.availability': 'متوفر على مدار السنة',

    'products.onion.title': 'بصل',
    'products.onion.desc': 'بصل طازج للتجزئة والجملة',
    'products.onion.fullDesc': 'بصل طازج مناسب للتجزئة والجملة وقطاع المطاعم مع تجهيز مطابق للتصدير.',
    'products.onion.origin': 'شمال الجزائر',
    'products.onion.packaging': 'أكياس شبكية، كراتين أو أكياس جملة',
    'products.onion.availability': 'متوفر على مدار السنة',

    'products.broccoli.title': 'بروكلي',
    'products.broccoli.desc': 'بروكلي طازج لقنوات التصدير',
    'products.broccoli.fullDesc': 'بروكلي طازج مختار لأسواق التصدير مع فرز ومراقبة جودة.',
    'products.broccoli.origin': 'شمال الجزائر',
    'products.broccoli.packaging': 'صناديق، كراتين أو عبوات مهواة',
    'products.broccoli.availability': 'موسمي وعلى مدار السنة حسب التوريد',

    'products.carrot.title': 'جزر',
    'products.carrot.desc': 'جزر طازج للتجزئة والجملة',
    'products.carrot.fullDesc': 'جزر طازج مجهز للتصدير بجودة وفرز متناسق.',
    'products.carrot.origin': 'شمال الجزائر',
    'products.carrot.packaging': 'أكياس، كراتين أو عبوات جملة',
    'products.carrot.availability': 'متوفر على مدار السنة',

    'products.cauliflower.title': 'قرنبيط',
    'products.cauliflower.desc': 'قرنبيط طازج للتصدير',
    'products.cauliflower.fullDesc': 'قرنبيط طازج مختار للتصدير مع فرز جودة وتجهيز مناسب لسلسلة التبريد.',
    'products.cauliflower.origin': 'شمال الجزائر',
    'products.cauliflower.packaging': 'صناديق، كراتين أو عبوات مهواة',
    'products.cauliflower.availability': 'موسمي وعلى مدار السنة حسب التوريد',

    'products.eggplant.title': 'باذنجان',
    'products.eggplant.desc': 'باذنجان طازج للأسواق الدولية',
    'products.eggplant.fullDesc': 'باذنجان طازج مجهز للتصدير بقياسات متناسقة وتعبئة مناسبة.',
    'products.eggplant.origin': 'شمال الجزائر',
    'products.eggplant.packaging': 'صناديق، كراتين أو عبوات جملة',
    'products.eggplant.availability': 'موسمي وعلى مدار السنة حسب التوريد',

    'products.peas.title': 'بزلاء',
    'products.peas.desc': 'بزلاء خضراء طازجة',
    'products.peas.fullDesc': 'بزلاء طازجة لقنوات التصدير وقطاع الأغذية مع تجهيز يركز على الجودة.',
    'products.peas.origin': 'شمال الجزائر',
    'products.peas.packaging': 'أكياس، كراتين أو تعبئة مخصصة',
    'products.peas.availability': 'متوفر موسمياً',

    'products.greenBeans.title': 'لوبياء',
    'products.greenBeans.desc': 'لوبياء طازجة للتصدير',
    'products.greenBeans.fullDesc': 'لوبياء طازجة مختارة للتصدير مع فرز وتعبئة بمعايير جودة.',
    'products.greenBeans.origin': 'شمال الجزائر',
    'products.greenBeans.packaging': 'صناديق، كراتين أو تعبئة مخصصة',
    'products.greenBeans.availability': 'موسمي وعلى مدار السنة حسب التوريد',

    'products.favaBeans.title': 'فول',
    'products.favaBeans.desc': 'فول طازج',
    'products.favaBeans.fullDesc': 'فول طازج مخصص لقنوات التصدير والجملة مع مراقبة جودة منتظمة.',
    'products.favaBeans.origin': 'شمال الجزائر',
    'products.favaBeans.packaging': 'أكياس، كراتين أو عبوات جملة',
    'products.favaBeans.availability': 'متوفر موسمياً',

    'products.cucumber.title': 'خيار',
    'products.cucumber.desc': 'خيار طازج للتجزئة والتصدير',
    'products.cucumber.fullDesc': 'خيار طازج مجهز لأسواق التصدير مع فرز وتعبئة مناسبة.',
    'products.cucumber.origin': 'شمال الجزائر',
    'products.cucumber.packaging': 'صناديق، كراتين أو عبوات جملة',
    'products.cucumber.availability': 'متوفر على مدار السنة',

    'products.zucchini.title': 'كوسة',
    'products.zucchini.desc': 'كوسة طازجة لقنوات التصدير',
    'products.zucchini.fullDesc': 'كوسة طازجة للتصدير بمقاسات متجانسة وتعبئة مضبوطة.',
    'products.zucchini.origin': 'شمال الجزائر',
    'products.zucchini.packaging': 'صناديق، كراتين أو عبوات جملة',
    'products.zucchini.availability': 'موسمي وعلى مدار السنة حسب التوريد',

    'products.pumpkin.title': 'يقطين',
    'products.pumpkin.desc': 'يقطين طازج للجملة والتصدير',
    'products.pumpkin.fullDesc': 'يقطين طازج لأسواق التصدير، متوفر بأحجام مختلفة مع خيارات تعبئة مناسبة.',
    'products.pumpkin.origin': 'شمال الجزائر',
    'products.pumpkin.packaging': 'صناديق، كراتين أو حاويات جملة',
    'products.pumpkin.availability': 'متوفر موسمياً',

    'products.vegetablesMixB.title': 'شوفلور، جزر، باذنجان، جلبانة، لوبياء',
    'products.vegetablesMixB.desc': 'تشكيلة خضروات طازجة متنوعة',
    'products.vegetablesMixB.fullDesc': 'خضروات للتصدير تشمل الشوفلور والجزر والباذنجان والجلبانة واللوبياء.',
    'products.vegetablesMixB.origin': 'شمال الجزائر',
    'products.vegetablesMixB.packaging': 'صناديق، كراتين أو تعبئة مخصصة',
    'products.vegetablesMixB.availability': 'موسمي وعلى مدار السنة حسب الصنف',

    'products.vegetablesMixC.title': 'فول، خيار، كوسة، يقطين',
    'products.vegetablesMixC.desc': 'خضروات مختارة طازجة',
    'products.vegetablesMixC.fullDesc': 'تشكيلة تصدير تشمل الفول والخيار والكوسة واليقطين.',
    'products.vegetablesMixC.origin': 'شمال الجزائر',
    'products.vegetablesMixC.packaging': 'صناديق، كراتين أو تعبئة مخصصة',
    'products.vegetablesMixC.availability': 'موسمي وعلى مدار السنة حسب الصنف',

    'products.artichoke.title': 'خرشوف (القرنون الشوكي)',
    'products.artichoke.desc': 'خرشوف طازج لأسواق التصدير',
    'products.artichoke.fullDesc': 'خرشوف عالي الجودة، بما في ذلك الأنواع المحلية، مجهز للتوزيع الدولي.',
    'products.artichoke.origin': 'شمال الجزائر',
    'products.artichoke.packaging': 'صناديق أو كراتين مهواة',
    'products.artichoke.availability': 'متوفر موسمياً',

    'products.fruitsMix.title': 'عنب، بطيخ، خوخ، فراولة، رمان',
    'products.fruitsMix.desc': 'تشكيلة فواكه طازجة موسمية',
    'products.fruitsMix.fullDesc': 'تشكيلة فواكه للتصدير تشمل العنب والبطيخ والخوخ والفراولة والرمان حسب الموسم.',
    'products.fruitsMix.origin': 'شمال الجزائر ',
    'products.fruitsMix.packaging': 'صناديق، علب فواكه، كراتين أو تعبئة مخصصة',
    'products.fruitsMix.availability': 'موسمي حسب نوع الفاكهة',

    'products.grapes.title': 'عنب',
    'products.grapes.desc': 'عنب طازج للمائدة',
    'products.grapes.fullDesc': 'عنب طازج مختار للتصدير مع فرز وتعبئة مضبوطة الجودة.',
    'products.grapes.origin': 'شمال الجزائر ',
    'products.grapes.packaging': 'علب فواكه، كراتين أو صناديق جملة',
    'products.grapes.availability': 'متوفر موسمياً',

    'products.watermelon.title': 'بطيخ',
    'products.watermelon.desc': 'بطيخ طازج لأسواق التصدير',
    'products.watermelon.fullDesc': 'بطيخ طازج مختار لبرامج التصدير مع تجهيز ونقل يراعي الجودة.',
    'products.watermelon.origin': 'شمال الجزائر',
    'products.watermelon.packaging': 'صناديق جملة أو تجهيز تصديري مخصص',
    'products.watermelon.availability': 'متوفر موسمياً',

    'products.peach.title': 'خوخ',
    'products.peach.desc': 'خوخ طازج بجودة تصديرية',
    'products.peach.fullDesc': 'خوخ طازج يتم حصاده وتعبئته للتوزيع الدولي مع فرز جودة.',
    'products.peach.origin': 'شمال الجزائر ',
    'products.peach.packaging': 'علب فواكه،  كراتين',
    'products.peach.availability': 'متوفر موسمياً',

    'products.strawberry.title': 'فراولة',
    'products.strawberry.desc': 'فراولة طازجة للأسواق الممتازة',
    'products.strawberry.fullDesc': 'فراولة طازجة مجهزة للتصدير والتجزئة مع تعبئة مناسبة لسلسلة التبريد.',
    'products.strawberry.origin': 'شمال الجزائر',
      'products.strawberry.packaging': 'علب صغيرة، عبوات  أو كراتين',
    'products.strawberry.availability': 'متوفر موسمياً',

    'products.pomegranate.title': 'رمان',
    'products.pomegranate.desc': 'رمان طازج للتصدير',
    'products.pomegranate.fullDesc': 'رمان طازج مختار لأسواق التصدير مع فرز وتعبئة بمعايير جودة.',
    'products.pomegranate.origin': 'شمال الجزائر ',
    'products.pomegranate.packaging': 'صناديق، كراتين أو عبوات جملة',
    'products.pomegranate.availability': 'متوفر موسمياً',
    
    'products.almonds.title': 'لوز ممتاز',
    'products.almonds.desc': 'لوز جزائري مقرمش',
    'products.almonds.fullDesc': 'لوز عالي الجودة معروف بنكهته الغنية وقيمته الغذائية. متوفر نيء، محمص، مقشر أو كمنتجات لوز.',
    'products.almonds.origin': 'منطقة الجزائرية (تلمسان، سعيدة، تندوف)',
    'products.almonds.packaging': 'أكياس مفرغة من الهواء، حاويات سائبة أو عبوات تجزئة',
    'products.almonds.availability': 'متوفر على مدار السنة',
    
    'products.oliveOil.title': 'زيت زيتون بكر ممتاز',
    'products.oliveOil.desc': 'زيت فاخر معصور على البارد',
    'products.oliveOil.fullDesc': 'زيت زيتون بكر ممتاز فاخر، معصور على البارد من زيتون منتقى يدوياً. غني بمضادات الأكسدة مع نكهة فاكهية مميزة.',
    'products.oliveOil.origin': 'الجزائر - منطقة القبائل (تزي وزو، بجاية، بومرداس)',
    'products.oliveOil.packaging': 'زجاجات،',
    'products.oliveOil.availability': 'حصاد جديد سنوياً (نوفمبر-فبراير)',
    
    'products.tomatoes.title': 'طماطم طازجة',
    'products.tomatoes.desc': 'جودة تصدير ناضجة على الكرمة',
    'products.tomatoes.fullDesc': 'طماطم فاخرة ناضجة على الكرمة مزروعة في ظروف مثالية. متوفرة بأنواع مختلفة ',
    'products.tomatoes.origin': 'شمال الجزائر',
    'products.tomatoes.packaging': 'صناديق مهواة، كراتين ',
    'products.tomatoes.availability': 'على مدار السنة مع موسم الذروة (مايو-أكتوبر)',
    
    'products.figs.title': 'تين طازج ومجفف',
    'products.figs.desc': 'تين جزائري حلو',
    'products.figs.fullDesc': 'تين عصاري متوفر طازجاً في موسمه أو كمنتجات مجففة فاخرة. معروف بحلاوته الطبيعية وفوائده الصحية.',
    'products.figs.origin': 'الجزائر ',
    'products.figs.packaging': 'طازج: صناديق ؛ مجفف: مفرغ من الهواء أو علب',
    'products.figs.availability': 'طازج (أغسطس-أكتوبر)، مجفف (على مدار السنة)',
    
    // Categories
    'category.olives': 'الزيتون ومنتجاته',
    'category.olives.desc': 'زيتون ممتاز وزيت زيتون تقليدي',
    'category.dates': 'التمور الممتازة',
    'category.dates.desc': 'تمور طبيعية وشهية',
    'category.citrus': 'حمضيات طازجة',
    'category.citrus.desc': 'حمضيات طازجة وعصيرية',
    'category.nuts': 'المكسرات الممتازة',
    'category.nuts.desc': 'مكسرات وجوز عالي الجودة',
    'category.food': 'مواد غذائية',
    'category.food.desc': 'شوكولاتة، حلويات/سكاكر، بسكويت/كوكيز، مستلزمات المعجنات والخبز، مشروبات غازية، عصائر ومياه',
    'category.vegetables': 'الخضروات الطازجة',
    'category.vegetables.desc': 'خضروات طازجة وعضوية',
    'category.fruits': 'الفواكه الطازجة',
    'category.fruits.desc': 'فواكه طبيعية وغذائية',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل معنا',
    'contact.form.name': 'اسمك',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.message': 'رسالتك',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.address': '16 شارع 1 نوفمبر ، الشلف 02000 - الجزائر',
    'contact.info.phone': '+213 5.59.30.04.17 /+213 7.75.12.98.71 /+213 5.62.08.59.02',
    'contact.info.email': 'bassatine.metidja.export@gmail.com',
    'contact.whatsapp': 'تحدث على واتساب',
    
    // WhatsApp
    'whatsapp.message': 'مرحبًا BM Export، أنا مهتم بخدمات التصدير الخاصة بكم.',
    
    // Footer
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.tagline': 'التميز في التصدير العالمي',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    const translated = translations[language][key as keyof typeof translations['en']];
    if (translated) {
      return translated;
    }

    return translations.en[key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
